apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversao
  template:
      metadata:
        labels:
          app: conversao
      spec:
        containers:
        - name: conversao
          image: ditols/aplicativo:v1.0
          ports:
           - containerPort: 80